services:
  web:
    image: php:8.4-apache
    volumes:
      - ./app:/var/www/html
      - ./apache.conf:/etc/apache2/sites-available/000-default.conf:ro
    ports:
      - 8080:80
    working_dir: /var/www/html
